=== Rubenmejzap12/LMSGI_UD4/Practicas/practicas.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT practicas (alumno)+>
    <!ATTLIST practicas xmlns CDATA #FIXED ''>

<!ELEMENT alumno (nif,resultado,(mac|(observaciones,ip)))>
    <!ATTLIST alumno xmlns CDATA #FIXED ''>

<!ELEMENT nif (#PCDATA)>
    <!ATTLIST nif xmlns CDATA #FIXED ''>

<!ELEMENT resultado (#PCDATA)>
    <!ATTLIST resultado xmlns CDATA #FIXED ''>

<!ELEMENT mac (#PCDATA)>
    <!ATTLIST mac xmlns CDATA #FIXED ''>

<!ELEMENT observaciones (#PCDATA)>
    <!ATTLIST observaciones xmlns CDATA #FIXED ''>

<!ELEMENT ip (#PCDATA)>
    <!ATTLIST ip xmlns CDATA #FIXED ''>

=== Rubenmejzap12/LMSGI_UD4/Practicas/practicas_DTD.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE practicas SYSTEM "practicas.dtd">
<practicas>
	<alumno>
		<nif>256987141K</nif>
		<resultado>Apto</resultado>
		<observaciones>Alumno con grandes notas y muy agradable</observaciones>
		<ip>156.168.1.1</ip> 
	</alumno>
	<alumno>
		<nif>25987454G</nif>
		<resultado>No Apto</resultado>
		<mac>45:FA:46:CA:45:13</mac>
	</alumno>
    <alumno>
		<nif>52658987J</nif>
		<resultado>Apto</resultado>
		<mac>45:FA:46:CA:45:13</mac>
	</alumno>
    <alumno>
		<nif>53256987F</nif>
		<resultado>No Apto</resultado>
        <observaciones>Alumno que no se esfuerza</observaciones>
		<ip>152.189.1.1</ip>
	</alumno>
</practicas>
