=== Rubenmejzap12/LMSGI_UD4/Libreria/casadellibro.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT libros (libro)+>
    <!ATTLIST libros xmlns CDATA #FIXED ''>

<!ELEMENT libro (autores,titulo,ISBN,editorial,fecha_publicacion,precio, precioaudiolibro)>
    <!ATTLIST libro xmlns CDATA #FIXED ''>

<!ELEMENT autores (autor)>
    <!ATTLIST autores xmlns CDATA #FIXED ''>

<!ELEMENT titulo (#PCDATA)>
    <!ATTLIST titulo xmlns CDATA #FIXED ''>

<!ELEMENT ISBN (#PCDATA)>
    <!ATTLIST ISBN xmlns CDATA #FIXED ''>

<!ELEMENT editorial (#PCDATA)>
    <!ATTLIST editorial xmlns CDATA #FIXED ''>

<!ELEMENT fecha_publicacion (#PCDATA)>
    <!ATTLIST fecha_publicacion xmlns CDATA #FIXED ''>

<!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio xmlns CDATA #FIXED ''>

<!ELEMENT precioaudiolibro (#PCDATA)>
    <!ATTLIST precioaudiolibro xmlns CDATA #FIXED ''>

<!ELEMENT autor (apellido1,apellido2,nombre)>
    <!ATTLIST autor xmlns CDATA #FIXED ''>

<!ELEMENT apellido1 (#PCDATA)>
    <!ATTLIST apellido1 xmlns CDATA #FIXED ''>

<!ELEMENT apellido2 (#PCDATA)>
    <!ATTLIST apellido2 xmlns CDATA #FIXED ''>

<!ELEMENT nombre (#PCDATA)>
    <!ATTLIST nombre xmlns CDATA #FIXED ''>

=== Rubenmejzap12/LMSGI_UD4/Libreria/casadellibro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "casadellibro.dtd">
<libros>
    <libro> 
        <autores>
            <autor>
                <apellido1>de Cervantes</apellido1>
                <apellido2>Ordo√±ez</apellido2>
                <nombre>Miguel</nombre>    
            </autor>
        </autores>
        <titulo>Don Quijote de la Mancha</titulo>
        <ISBN>4879874654</ISBN>
        <editorial>Francisco de Robles</editorial>
        <fecha_publicacion>1605</fecha_publicacion>
        <precio>12</precio>
        <precioaudiolibro>10</precioaudiolibro>  
    </libro>
    <libro> 
        <autores>
            <autor>
                <apellido1>Cercas</apellido1>
                <apellido2>Gongora</apellido2>
                <nombre>Javier</nombre>    
            </autor>
        </autores>
        <titulo>Soldados de Salamina</titulo>
        <ISBN>4587954874</ISBN>
        <editorial>Alfaguara</editorial>
        <fecha_publicacion>2001</fecha_publicacion>
        <precio>9</precio>
        <precioaudiolibro>3</precioaudiolibro>   
    </libro>
    <libro> 
        <autores>
            <autor>
                <apellido1>Ruiz</apellido1>
                <apellido2>Zafon</apellido2>
                <nombre>Carlos</nombre>    
            </autor>
        </autores>
        <titulo>La sombra del viento</titulo>
        <ISBN>7845152489</ISBN>
        <editorial>Anaya</editorial>
        <fecha_publicacion>2001</fecha_publicacion> 
        <precio>20</precio>
        <precioaudiolibro>7</precioaudiolibro>  
    </libro>
    <libro> 
    <autores>
        <autor>
            <apellido1>San Pedro</apellido1>
            <apellido2></apellido2>
            <nombre>Jose Luis</nombre>    
        </autor>
    </autores>
    <titulo>La sonrisa etrusca</titulo>
    <ISBN>1245469836</ISBN>
    <editorial>Alfaguara</editorial>
    <fecha_publicacion>1985</fecha_publicacion>
    <precio>18</precio>  
    <precioaudiolibro>5</precioaudiolibro> 
    </libro>
    <libro> 
    <autores>
        <autor>
            <apellido1>De Rojas</apellido1>
            <apellido2>Salcedo</apellido2>
            <nombre>Fernando</nombre>    
        </autor>
    </autores>
    <titulo>La Celestina</titulo>
    <ISBN>1548965478</ISBN>
    <editorial>Burgos</editorial>
    <fecha_publicacion>1499 </fecha_publicacion>
    <precio>11</precio>
    <precioaudiolibro>4</precioaudiolibro> 
    </libro>
</libros>
