=== Rubenmejzap12/LMSGI_UD4/Modulos/modulos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="modulos">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="contenidos"/>
        <xs:element ref="nombre"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="contenidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bloque"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="bloque">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="UnidadDidactica"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="UnidadDidactica">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tipo"/>
        <xs:element ref="descripcion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tipo" type="xs:string"/>
  <xs:element name="descripcion" type="xs:string"/>
  <xs:element name="nombre" type="xs:string"/>
</xs:schema>

=== Rubenmejzap12/LMSGI_UD4/Modulos/modulos_X.xml
<?xml version="1.0" encoding="utf-8"?>
<modulos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modulos.xsd">
        <nombre> Lenguaje de marcas </nombre>
        <contenidos>
            <bloque>
                <UnidadDidactica>
                    <tipo>lenguaje de transformacion</tipo>
                    <descripcion>Consta de ficheros xml, dtd y xsd</descripcion>
                </UnidadDidactica>	 
            </bloque>
        </contenidos>
        <nombre> Programacion </nombre>
        <contenidos>
            <bloque>
                <UnidadDidactica>
                    <tipo>Java FX</tipo>
                    <descripcion>Aplicacion de juego con Java FX</descripcion>
                </UnidadDidactica>	 
            </bloque>
        </contenidos>
        <nombre> Base de datos </nombre>
        <contenidos>
            <bloque>
                <UnidadDidactica>
                    <tipo> Lenguaje SQL y DDL </tipo>
                    <descripcion> Transformacion de Base de datos a DDL</descripcion>
                </UnidadDidactica>	 
            </bloque>
        </contenidos>
</modulos>
