=== Rubenmejzap12/LMSGI_UD4/Clientes/clientes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    version="0.1" xml:lang="es">
    <xs:annotation>
        <xs:documentation xml:lang="Es-es">
            Esquema para el alta de clientes sede central
            <fecha>2022-01-25</fecha>
            <autor>Ruben MejÃ­as Zapata</autor>
        </xs:documentation>
    </xs:annotation>
	<xs:element name="clientes">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="sede" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" maxOccurs="unbounded" name="direccion" type="xs:string" />
                            <xs:element name="empleado" type="xs:string" />
                            <xs:element name="fecha_Alta" type="xs:date" />
                            <xs:element name="descripcion" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Trabajador"/>
                                        <xs:enumeration value="No Trabajador"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="cliente" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numViviendas" type="xs:positiveInteger" />
                                        <xs:element name="costeVivienda" type="xs:decimal" />
                                        <xs:element name="resumenViviendas" type="xs:string" />
                                        <xs:element name="plazoAlta" type="xs:date" />
                                    </xs:sequence>
                                    <xs:attribute name="codigo" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[A-Z]{1}[0-9]{8}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="codigoCliente" use="required" />
                    </xs:complexType>
                </xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <xs:simpleType name="codigoCliente">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{1}[0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Rubenmejzap12/LMSGI_UD4/Clientes/clientes_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clientes.xsd">
    <sede codigo="C15896325">
        <direccion>c/ Asuncion</direccion>
        <empleado> Juan Ignacion Martinez Jaime </empleado>
        <fecha_Alta>2019-05-01</fecha_Alta>
        <descripcion>Trabajador</descripcion>
        <cliente codigo="G45896324">
            <numViviendas>4</numViviendas>
            <costeVivienda>175.000</costeVivienda>
            <resumenViviendas>Embargada</resumenViviendas>
            <plazoAlta>2019-10-05</plazoAlta>
        </cliente>
        <cliente codigo="J56957546">
            <numViviendas>1</numViviendas>
            <costeVivienda>110.000</costeVivienda>
            <resumenViviendas>Terminada</resumenViviendas>
            <plazoAlta>2020-05-15</plazoAlta>
        </cliente>
    </sede>
    <sede codigo="L74185236">
        <direccion>C/ Canalejas</direccion>
        <empleado>Antonio Linares Cuenca</empleado>
        <fecha_Alta>2017-02-15</fecha_Alta>
        <descripcion>Trabajador</descripcion>
        <cliente codigo="F85296378">
            <numViviendas>4</numViviendas>
            <costeVivienda>123.000</costeVivienda>
            <resumenViviendas>En Reforma</resumenViviendas>
            <plazoAlta>2019-05-12</plazoAlta>
        </cliente>
        <cliente codigo="L54897412">
            <numViviendas>2</numViviendas>
            <costeVivienda>190.000</costeVivienda>
            <resumenViviendas>Perfecto Estado</resumenViviendas>
            <plazoAlta>2020-06-25</plazoAlta>
        </cliente>
    </sede>
</clientes>
