=== Rubenmejzap12/LMSGI_UD4/BDsms/telegram.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="contactos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="contacto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contacto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="telefono"/>
        <xs:element ref="fechaguardado"/>
        <xs:element ref="horaConexion"/>
        <xs:element ref="ultimoMensaje"/>
        <xs:element ref="estado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string"/>
  <xs:element name="telefono" type="xs:integer"/>
  <xs:element name="fechaguardado" type="xs:string"/>
  <xs:element name="horaConexion" type="xs:NMTOKEN"/>
  <xs:element name="ultimoMensaje" type="xs:string"/>
  <xs:element name="estado" type="xs:string"/>
</xs:schema>

=== Rubenmejzap12/LMSGI_UD4/BDsms/telegram_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<contactos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="telegram.xsd">
        <contacto>
            <nombre> Luis </nombre>
            <telefono> 659654896 </telefono>
            <fechaguardado> 1/7/2015 </fechaguardado>
            <horaConexion> 23:55 </horaConexion>
            <ultimoMensaje> Hasta luego </ultimoMensaje>
            <estado> Disponible </estado>
        </contacto>
        <contacto>
            <nombre> Ana </nombre>
            <telefono> 659654896 </telefono>
            <fechaguardado> 12/4/2010 </fechaguardado>
            <horaConexion> 12:50 </horaConexion>
            <ultimoMensaje> Hola </ultimoMensaje>
            <estado> Trabajando </estado>
        </contacto>
        <contacto>
            <nombre> Enrique </nombre>
            <telefono> 758514896 </telefono>
            <fechaguardado> 2/2/2018 </fechaguardado>
            <horaConexion> 13:52 </horaConexion>
            <ultimoMensaje> De acuerdo </ultimoMensaje>
            <estado> No Disponible </estado>
        </contacto>
        <contacto>
            <nombre> Antonio </nombre>
            <telefono> 658654896 </telefono>
            <fechaguardado> 12/5/2009 </fechaguardado>
            <horaConexion> 18:32 </horaConexion>
            <ultimoMensaje> Voy a buscarte </ultimoMensaje>
            <estado> Disponible </estado>
        </contacto>
        <contacto>
            <nombre> Juan Manuel </nombre>
            <telefono> 689321456 </telefono>
            <fechaguardado> 19/7/2020 </fechaguardado>
            <horaConexion> 16:16 </horaConexion>
            <ultimoMensaje> Lo siento, no her podido asistir </ultimoMensaje>
            <estado> En el trabajo </estado>
        </contacto>
    </contactos>
