=== Rubenmejzap12/LMSGI_UD4/Concesionario/Elmotorista.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="concesionario">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="moto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="moto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="codigo"/>
        <xs:element ref="marca"/>
        <xs:element ref="modelo"/>
        <xs:element ref="matricula"/>
        <xs:element ref="potencia"/>
        <xs:element ref="tipomoto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="codigo" type="xs:integer"/>
  <xs:element name="marca" type="xs:NCName"/>
  <xs:element name="modelo" type="xs:NMTOKEN"/>
  <xs:element name="matricula" type="xs:NMTOKEN"/>
  <xs:element name="potencia" type="xs:integer"/>
  <xs:element name="tipomoto" type="xs:NCName"/>
</xs:schema>

=== Rubenmejzap12/LMSGI_UD4/Concesionario/Elmotorista_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Elmotorista.xsd">
    <moto>
        <codigo>1</codigo>
        <marca>Yamaha</marca>
        <modelo>R1</modelo>
        <matricula>1020LKD</matricula>
        <potencia>120</potencia>
        <tipomoto>Carretera</tipomoto>
    </moto>
    <moto>
        <codigo>2</codigo>
        <marca>KTM</marca>
        <modelo>530</modelo>
        <matricula>4928lDV</matricula>
        <potencia>50</potencia>
        <tipomoto>Cross</tipomoto>
    </moto>
    <moto>
        <codigo>3</codigo>
        <marca>Kawasaki</marca>
        <modelo>Ninja</modelo>
        <matricula>4896KHG</matricula>
        <potencia>100</potencia>
        <tipomoto>carretera</tipomoto>
    </moto>
    <moto>
        <codigo>4</codigo>
        <marca>YAMAHA</marca>
        <modelo>TMAX</modelo>
        <matricula>4928LDU</matricula>
        <potencia>60</potencia>
        <tipomoto>Bespa</tipomoto>
    </moto>
    <moto>
        <codigo>5</codigo>
        <marca>Honda</marca>
        <modelo>CBR</modelo>
        <matricula>4589LHJ</matricula>
        <potencia>100</potencia>
        <tipomoto>Carretera</tipomoto>
    </moto>
</concesionario>
